### ISSUE TITLE
1.新代码多通道改单通道后，那原来预训练好的模型是不是无法进行预测了？2.predict.p运行错误，报错原因我看一是有您本地文件信息导致错误，二是数据shape错误。

### ISSUE THREAD

**Issue by YexfSC** [yeyupiaoling/PPASR#113]
报错信息：
Traceback (most recent call last):
  File "infer_path.py", line 36, in <module>
    pun_model_dir=args.pun_model_dir)
  File "/home/bml/storage/PPASR-master-UPDATE/ppasr/predict.py", line 119, in __init__
    self.predict(audio_ndarray=warmup_audio, is_itn=False)
  File "/home/bml/storage/PPASR-master-UPDATE/ppasr/predict.py", line 194, in predict
    self.predictor.run()
ValueError: In user code:

    File "E:\yeyupiaoling\PyCharm\PyCharm\PPASR\export_model.py", line 25, in <module>
      trainer.export(save_model_path=args.save_model, resume_model=args.resume_model.format(args.use_model, args.feature_method))
    File "E:\yeyupiaoling\PyCharm\PyCharm\PPASR\ppasr\trainer.py", line 581, in export
      paddle.jit.save(layer=model, path=infer_model_path, input_spec=input_spec)
    File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\dygraph\jit.py", line 631, in wrapper
      func(layer, path, input_spec, **configs)
    File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\dygraph\jit.py", line 871, in save
      concrete_program = static_forward.concrete_program_specify_input_spec(
    File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 527, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 436, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 801, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 785, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 733, in from_func_spec
      outputs = static_func(*inputs)
    File "E:\yeyupiaoling\PyCharm\PyCharm\PPASR\ppasr\model_utils\utils.py", line 33, in forward
      x = self.normalizer(audio)
    File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "E:\yeyupiaoling\PyCharm\PyCharm\PPASR\ppasr\model_utils\utils.py", line 19, in forward
      x = (x - self.mean) / self.std
    File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\layers\math_op_patch.py", line 342, in __impl__
      current_block(self).append_op(
    File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\framework.py", line 3615, in append_op
      op = Operator(
    File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\framework.py", line 2635, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 837, 80] and the shape of Y = [161]. Received [80] in X is not equal to [161] in Y at i:2.
      [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/phi/kernels/funcs/common_shape.h:84)
      [operator < elementwise_sub > error]

**Comment by yeyupiaoling** [comment]
不是，你用错误配置文件了。要配套使用的，configs目录下的

**Comment by YexfSC** [comment]
嗯呢，确实是配置错误
