### ISSUE TITLE
博主您好，我在使用预训练模型时遇到了这个错误，可以帮我看下吗？

### ISSUE THREAD

**Issue by wxy0505** [yeyupiaoling/PPASR#123]
`/home/hao/anaconda3/envs/ctc/bin/python3.8 /home/hao/PPASR-develop/train.py 
/home/hao/anaconda3/envs/ctc/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
[2022-11-26 10:57:31.001002 INFO   ] utils:print_arguments:18 - ----------- 额外配置参数 -----------
[2022-11-26 10:57:31.001087 INFO   ] utils:print_arguments:20 - augment_conf_path: configs/augmentation.json
[2022-11-26 10:57:31.001127 INFO   ] utils:print_arguments:20 - configs: configs/conformer_online_zh.yml
[2022-11-26 10:57:31.001160 INFO   ] utils:print_arguments:20 - pretrained_model: /home/hao/PPASR-develop/lm/zh_giga.no_cna_cmn.prune01244.klm
[2022-11-26 10:57:31.001191 INFO   ] utils:print_arguments:20 - resume_model: /home/hao/PPASR-develop/lm/zh_giga.no_cna_cmn.prune01244.klm
[2022-11-26 10:57:31.001221 INFO   ] utils:print_arguments:20 - save_model_path: models/
[2022-11-26 10:57:31.001250 INFO   ] utils:print_arguments:20 - use_gpu: True
[2022-11-26 10:57:31.001280 INFO   ] utils:print_arguments:21 - ------------------------------------------------
[2022-11-26 10:57:31.001308 INFO   ] utils:print_arguments:22 - ----------- 配置文件参数 -----------
[2022-11-26 10:57:31.001341 INFO   ] utils:print_arguments:25 - ctc_beam_search_decoder_conf:
[2022-11-26 10:57:31.001376 INFO   ] utils:print_arguments:27 -  alpha: 2.2
[2022-11-26 10:57:31.001416 INFO   ] utils:print_arguments:27 -  beam_size: 300
[2022-11-26 10:57:31.001447 INFO   ] utils:print_arguments:27 -  beta: 4.3
[2022-11-26 10:57:31.001477 INFO   ] utils:print_arguments:27 -  cutoff_prob: 0.99
[2022-11-26 10:57:31.001506 INFO   ] utils:print_arguments:27 -  cutoff_top_n: 40
[2022-11-26 10:57:31.001544 INFO   ] utils:print_arguments:27 -  language_model_path: lm/zh_giga.no_cna_cmn.prune01244.klm
[2022-11-26 10:57:31.001574 INFO   ] utils:print_arguments:27 -  num_processes: 10
[2022-11-26 10:57:31.001603 INFO   ] utils:print_arguments:25 - dataset_conf:
[2022-11-26 10:57:31.001635 INFO   ] utils:print_arguments:27 -  batch_size: 16
[2022-11-26 10:57:31.001664 INFO   ] utils:print_arguments:27 -  dataset_vocab: dataset/vocabulary.txt
[2022-11-26 10:57:31.001693 INFO   ] utils:print_arguments:27 -  manifest_type: txt
[2022-11-26 10:57:31.001721 INFO   ] utils:print_arguments:27 -  max_duration: 20
[2022-11-26 10:57:31.001750 INFO   ] utils:print_arguments:27 -  mean_istd_path: dataset/mean_istd.json
[2022-11-26 10:57:31.001779 INFO   ] utils:print_arguments:27 -  min_duration: 0.5
[2022-11-26 10:57:31.001808 INFO   ] utils:print_arguments:27 -  noise_manifest_path: dataset/manifest.noise
[2022-11-26 10:57:31.001837 INFO   ] utils:print_arguments:27 -  num_workers: 4
[2022-11-26 10:57:31.001867 INFO   ] utils:print_arguments:27 -  prefetch_factor: 100
[2022-11-26 10:57:31.001895 INFO   ] utils:print_arguments:27 -  test_manifest: dataset/manifest.test
[2022-11-26 10:57:31.001924 INFO   ] utils:print_arguments:27 -  train_manifest: dataset/manifest.train
[2022-11-26 10:57:31.001953 INFO   ] utils:print_arguments:27 -  use_shared_memory: True
[2022-11-26 10:57:31.001982 INFO   ] utils:print_arguments:29 - decoder: ctc_beam_search
[2022-11-26 10:57:31.002011 INFO   ] utils:print_arguments:25 - decoder_conf:
[2022-11-26 10:57:31.002042 INFO   ] utils:print_arguments:27 -  attention_heads: 4
[2022-11-26 10:57:31.002072 INFO   ] utils:print_arguments:27 -  dropout_rate: 0.1
[2022-11-26 10:57:31.002101 INFO   ] utils:print_arguments:27 -  linear_units: 1024
[2022-11-26 10:57:31.002130 INFO   ] utils:print_arguments:27 -  num_blocks: 3
[2022-11-26 10:57:31.002159 INFO   ] utils:print_arguments:27 -  positional_dropout_rate: 0.1
[2022-11-26 10:57:31.002188 INFO   ] utils:print_arguments:27 -  r_num_blocks: 3
[2022-11-26 10:57:31.002218 INFO   ] utils:print_arguments:27 -  self_attention_dropout_rate: 0.1
[2022-11-26 10:57:31.002247 INFO   ] utils:print_arguments:27 -  src_attention_dropout_rate: 0.1
[2022-11-26 10:57:31.002276 INFO   ] utils:print_arguments:25 - encoder_conf:
[2022-11-26 10:57:31.002307 INFO   ] utils:print_arguments:27 -  activation_type: swish
[2022-11-26 10:57:31.002337 INFO   ] utils:print_arguments:27 -  attention_dropout_rate: 0.1
[2022-11-26 10:57:31.002366 INFO   ] utils:print_arguments:27 -  attention_heads: 4
[2022-11-26 10:57:31.002395 INFO   ] utils:print_arguments:27 -  cnn_module_kernel: 15
[2022-11-26 10:57:31.002424 INFO   ] utils:print_arguments:27 -  dropout_rate: 0.1
[2022-11-26 10:57:31.002453 INFO   ] utils:print_arguments:27 -  input_layer: conv2d
[2022-11-26 10:57:31.002482 INFO   ] utils:print_arguments:27 -  linear_units: 2048
[2022-11-26 10:57:31.002511 INFO   ] utils:print_arguments:27 -  normalize_before: True
[2022-11-26 10:57:31.002539 INFO   ] utils:print_arguments:27 -  num_blocks: 12
[2022-11-26 10:57:31.002568 INFO   ] utils:print_arguments:27 -  output_size: 256
[2022-11-26 10:57:31.002596 INFO   ] utils:print_arguments:27 -  pos_enc_layer_type: rel_pos
[2022-11-26 10:57:31.002625 INFO   ] utils:print_arguments:27 -  positional_dropout_rate: 0.1
[2022-11-26 10:57:31.002655 INFO   ] utils:print_arguments:27 -  use_cnn_module: True
[2022-11-26 10:57:31.002684 INFO   ] utils:print_arguments:29 - metrics_type: cer
[2022-11-26 10:57:31.002713 INFO   ] utils:print_arguments:25 - model_conf:
[2022-11-26 10:57:31.002744 INFO   ] utils:print_arguments:27 -  ctc_weight: 0.3
[2022-11-26 10:57:31.002774 INFO   ] utils:print_arguments:27 -  length_normalized_loss: False
[2022-11-26 10:57:31.002803 INFO   ] utils:print_arguments:27 -  lsm_weight: 0.1
[2022-11-26 10:57:31.002833 INFO   ] utils:print_arguments:27 -  reverse_weight: 0.3
[2022-11-26 10:57:31.002861 INFO   ] utils:print_arguments:25 - optimizer_conf:
[2022-11-26 10:57:31.002892 INFO   ] utils:print_arguments:27 -  learning_rate: 0.001
[2022-11-26 10:57:31.002922 INFO   ] utils:print_arguments:27 -  min_lr: 1e-5
[2022-11-26 10:57:31.002950 INFO   ] utils:print_arguments:27 -  optimizer: Adam
[2022-11-26 10:57:31.002979 INFO   ] utils:print_arguments:27 -  warmup_steps: 25000
[2022-11-26 10:57:31.003007 INFO   ] utils:print_arguments:27 -  weight_decay: 1e-6
[2022-11-26 10:57:31.003037 INFO   ] utils:print_arguments:25 - preprocess_conf:
[2022-11-26 10:57:31.003067 INFO   ] utils:print_arguments:27 -  feature_method: fbank
[2022-11-26 10:57:31.003096 INFO   ] utils:print_arguments:27 -  n_mels: 80
[2022-11-26 10:57:31.003124 INFO   ] utils:print_arguments:27 -  n_mfcc: 40
[2022-11-26 10:57:31.003153 INFO   ] utils:print_arguments:27 -  sample_rate: 16000
[2022-11-26 10:57:31.003181 INFO   ] utils:print_arguments:27 -  target_dB: -20
[2022-11-26 10:57:31.003209 INFO   ] utils:print_arguments:27 -  use_dB_normalization: True
[2022-11-26 10:57:31.003238 INFO   ] utils:print_arguments:25 - train_conf:
[2022-11-26 10:57:31.003268 INFO   ] utils:print_arguments:27 -  accum_grad: 4
[2022-11-26 10:57:31.003298 INFO   ] utils:print_arguments:27 -  grad_clip: 5.0
[2022-11-26 10:57:31.003326 INFO   ] utils:print_arguments:27 -  log_interval: 100
[2022-11-26 10:57:31.003355 INFO   ] utils:print_arguments:27 -  max_epoch: 600
[2022-11-26 10:57:31.003384 INFO   ] utils:print_arguments:29 - use_model: conformer_online
[2022-11-26 10:57:31.003412 INFO   ] utils:print_arguments:30 - ------------------------------------------------
[2022-11-26 10:57:31.003987 WARNING] augmentation:_parse_pipeline_from:127 - dataset/manifest.noise不存在，已经忽略噪声增强操作！
[2022-11-26 10:57:31.004073 INFO   ] augmentation:_parse_pipeline_from:129 - 数据增强配置：{'type': 'resample', 'aug_type': 'audio', 'params': {'new_sample_rate': [8000, 32000, 44100, 48000]}, 'prob': 1.0}
[2022-11-26 10:57:31.004120 INFO   ] augmentation:_parse_pipeline_from:129 - 数据增强配置：{'type': 'speed', 'aug_type': 'audio', 'params': {'min_speed_rate': 0.9, 'max_speed_rate': 1.1, 'num_rates': 3}, 'prob': 1.0}
[2022-11-26 10:57:31.004166 INFO   ] augmentation:_parse_pipeline_from:129 - 数据增强配置：{'type': 'shift', 'aug_type': 'audio', 'params': {'min_shift_ms': -5, 'max_shift_ms': 5}, 'prob': 1.0}
[2022-11-26 10:57:31.004204 INFO   ] augmentation:_parse_pipeline_from:129 - 数据增强配置：{'type': 'volume', 'aug_type': 'audio', 'params': {'min_gain_dBFS': -15, 'max_gain_dBFS': 15}, 'prob': 1.0}
[2022-11-26 10:57:31.004410 INFO   ] augmentation:_parse_pipeline_from:129 - 数据增强配置：{'type': 'specaug', 'aug_type': 'feature', 'params': {'inplace': True, 'max_time_warp': 5, 'max_t_ratio': 0.05, 'n_freq_masks': 2, 'max_f_ratio': 0.15, 'n_time_masks': 2, 'replace_with_zero': False}, 'prob': 1.0}
[2022-11-26 10:57:31.004462 INFO   ] augmentation:_parse_pipeline_from:129 - 数据增强配置：{'type': 'specsub', 'aug_type': 'feature', 'params': {'max_t': 30, 'num_t_sub': 3}, 'prob': 1.0}
W1126 10:57:31.426664  3103 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.2
W1126 10:57:31.428241  3103 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
[2022-11-26 10:57:32.052310 INFO   ] trainer:train:437 - 训练数据：134424
Traceback (most recent call last):
  File "/home/hao/anaconda3/envs/ctc/lib/python3.8/site-packages/paddle/framework/io.py", line 954, in load
    load_result = pickle.load(f, encoding='latin1')
_pickle.UnpicklingError: invalid load key, 'm'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hao/anaconda3/envs/ctc/lib/python3.8/site-packages/paddle/framework/io.py", line 980, in load
    tensor, _ = _load_selected_rows(path)
  File "/home/hao/anaconda3/envs/ctc/lib/python3.8/site-packages/paddle/framework/io.py", line 541, in _load_selected_rows
    _seek = core.load_selected_rows(temp_sr, file_name)
ValueError: (InvalidArgument) Only version 0 SelectedRows is supported.
  [Hint: Expected version == 0U, but received version:1885433197 != 0U:0.] (at /paddle/paddle/fluid/framework/selected_rows_utils.cc:68)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hao/anaconda3/envs/ctc/lib/python3.8/site-packages/paddle/framework/io.py", line 984, in load
    tensor, _ = _load_lod_tensor(path)
  File "/home/hao/anaconda3/envs/ctc/lib/python3.8/site-packages/paddle/framework/io.py", line 502, in _load_lod_tensor
    _seek = paddle.fluid.core.load_lod_tensor(temp_t, file_name)
ValueError: (InvalidArgument) Deserialize to tensor failed, maybe the loaded file is not a paddle model(expected file format: 0, but 1885433197 found).
  [Hint: Expected version == 0U, but received version:1885433197 != 0U:0.] (at /paddle/paddle/fluid/framework/lod_tensor.cc:276)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hao/anaconda3/envs/ctc/lib/python3.8/site-packages/paddle/framework/io.py", line 995, in load
    program = Program.parse_from_string(
  File "/home/hao/anaconda3/envs/ctc/lib/python3.8/site-packages/paddle/fluid/framework.py", line 5762, in parse_from_string
    p.desc = core.ProgramDesc(binary_str)
ValueError: (InvalidArgument) Failed to parse program_desc from binary string.
  [Hint: Expected desc_.ParseFromString(binary_str) == true, but received desc_.ParseFromString(binary_str):0 != true:1.] (at /paddle/paddle/fluid/framework/program_desc.cc:103)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hao/PPASR-develop/train.py", line 27, in <module>
    trainer.train(save_model_path=args.save_model_path,
  File "/home/hao/PPASR-develop/ppasr/trainer.py", line 439, in train
    self.__load_pretrained(pretrained_model=pretrained_model)
  File "/home/hao/PPASR-develop/ppasr/trainer.py", line 171, in __load_pretrained
    model_state_dict = paddle.load(pretrained_model)
  File "/home/hao/anaconda3/envs/ctc/lib/python3.8/site-packages/paddle/framework/io.py", line 999, in load
    raise ValueError(
ValueError: `paddle.load` can not parse the file:/home/hao/PPASR-develop/lm/zh_giga.no_cna_cmn.prune01244.klm.`

**Comment by yeyupiaoling** [comment]
你怎么把语言模型作为预训练模型加载了？

**Comment by wxy0505** [comment]
好的，这个我懂了
