### ISSUE TITLE
执行train.py 出错了

### ISSUE THREAD

**Issue by new786786** [yeyupiaoling/PPASR#133]
Traceback (most recent call last):
  File "H:/asr/PPASR-develop/train.py", line 25, in <module>
    augment_conf_path=args.augment_conf_path)
  File "H:\asr\PPASR-develop\ppasr\trainer.py", line 474, in train
    self.__setup_dataloader(augment_conf_path=augment_conf_path, is_train=True)
  File "H:\asr\PPASR-develop\ppasr\trainer.py", line 102, in __setup_dataloader
    num_workers=self.configs.dataset_conf.num_workers)
TypeError: __init__() got an unexpected keyword argument 'prefetch_factor'

**Comment by yeyupiaoling** [comment]
你用了旧的配置文件，参考新的配置文件，复制对应的字段进去就行了

**Comment by new786786** [comment]
这个项目刚刚复制使用了

**Comment by yeyupiaoling** [comment]
只复制缺少的就行了

**Comment by DannyWang920** [comment]
在哪参考新的配置文件呢
