### ISSUE TITLE
你好，我昨天才下载的代码，怎么还是会train报这个错

### ISSUE THREAD

**Issue by DannyWang920** [yeyupiaoling/PPASR#162]
Traceback (most recent call last):
  File "E:/ASR/PPASR-develop/train.py", line 25, in <module>
    augment_conf_path=args.augment_conf_path)
  File "E:\ASR\PPASR-develop\ppasr\trainer.py", line 476, in train
    self.__setup_dataloader(augment_conf_path=augment_conf_path, is_train=True)
  File "E:\ASR\PPASR-develop\ppasr\trainer.py", line 100, in __setup_dataloader
    num_workers=self.configs.dataset_conf.num_workers)
TypeError: __init__() got an unexpected keyword argument 'prefetch_factor'

Process finished with exit code 1

**Comment by yeyupiaoling** [comment]
你升级一下paddlepaddle
