### ISSUE TITLE
你好我训练的时候报错，请问你知道怎么解决吗

### ISSUE THREAD

**Issue by DannyWang920** [yeyupiaoling/PPASR#165]
Traceback (most recent call last):
  File "E:/ASR/PPASR-develop/train.py", line 22, in <module>
    trainer.train(save_model_path=args.save_model_path,
  File "E:\ASR\PPASR-develop\ppasr\trainer.py", line 476, in train
    self.__setup_dataloader(augment_conf_path=augment_conf_path, is_train=True)
  File "E:\ASR\PPASR-develop\ppasr\trainer.py", line 98, in __setup_dataloader
    use_shared_memory=self.configs.dataset_conf.use_shared_memory,
KeyError: 'use_shared_memory'

**Comment by yeyupiaoling** [comment]
应该是paddlepaddle版本问题，你升级一下。

**Comment by DannyWang920** [comment]
> 

我就是2.4.1 cuda11.6

**Comment by yeyupiaoling** [comment]
你看看你的配置文件里有没有这个参数

**Comment by DannyWang920** [comment]
> 你看看你的配置文件里有没有这个参数

无

**Comment by yeyupiaoling** [comment]
> > 你看看你的配置文件里有没有这个参数
> 
> 无
> 

那应该是你用了旧的配置文件
