### ISSUE TITLE
执行python creat_data.py时报错

### ISSUE THREAD

**Issue by ghost** [yeyupiaoling/PPASR#181]
(masr) nvidia@tegra-ubuntu:~/MASR$ python create_data.py 
Traceback (most recent call last):
  File "/home/nvidia/MASR/create_data.py", line 4, in <module>
    from masr.trainer import MASRTrainer
  File "/home/nvidia/MASR/masr/trainer.py", line 21, in <module>
    from masr.data_utils.featurizer.audio_featurizer import AudioFeaturizer
  File "/home/nvidia/MASR/masr/data_utils/featurizer/audio_featurizer.py", line 3, in <module>
    from torchaudio.compliance.kaldi import mfcc, fbank
  File "/home/nvidia/miniconda3/envs/masr/lib/python3.11/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/home/nvidia/miniconda3/envs/masr/lib/python3.11/site-packages/torchaudio/_extension/__init__.py", line 43, in <module>
    _load_lib("libtorchaudio")
  File "/home/nvidia/miniconda3/envs/masr/lib/python3.11/site-packages/torchaudio/_extension/utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "/home/nvidia/miniconda3/envs/masr/lib/python3.11/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/home/nvidia/miniconda3/envs/masr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /home/nvidia/miniconda3/envs/masr/lib/python3.11/site-packages/torchaudio/lib/[libtorchaudio.so](http://libtorchaudio.so/): undefined symbol: _ZNK5torch8autograd4Node4nameEv

**Comment by yeyupiaoling** [comment]
看样子torchaudio是的动态库有问题，你重新安装一下，用conda安装
