### ISSUE TITLE
执行python create_data.py报错importerror

### ISSUE THREAD

**Issue by yx1525** [yeyupiaoling/PPASR#182]
Error: Can not import paddle core while this file exists: /home/xuyang/anaconda3/envs/ppasr/lib/python3.7/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "create_data.py", line 4, in <module>
    from ppasr.trainer import PPASRTrainer
  File "/home/xuyang/PPASR/ppasr/trainer.py", line 12, in <module>
    import paddle
  File "/home/xuyang/anaconda3/envs/ppasr/lib/python3.7/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/home/xuyang/anaconda3/envs/ppasr/lib/python3.7/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/xuyang/anaconda3/envs/ppasr/lib/python3.7/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/home/xuyang/anaconda3/envs/ppasr/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/xuyang/anaconda3/envs/ppasr/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/xuyang/anaconda3/envs/ppasr/lib/python3.7/site-packages/paddle/fluid/core.py", line 304, in <module>
    raise e
  File "/home/xuyang/anaconda3/envs/ppasr/lib/python3.7/site-packages/paddle/fluid/core.py", line 249, in <module>
    from . import libpaddle
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory

**Comment by yeyupiaoling** [comment]
@yx1525 这个是你Python本身有问题，可以重新创建一个Python虚拟环境
