### ISSUE TITLE
安装解码器报错

### ISSUE THREAD

**Issue by account15222** [yeyupiaoling/PPASR#186]
现在安装python -m pip install paddlespeech_ctcdecoders -U -i https://ppasr.yeyupiaoling.cn/pypi/simple/这个解码器后报错了，默认的话不报错

这是报错信息
Traceback (most recent call last):
  File "/root/anaconda3/envs/asr/lib/python3.8/site-packages/paddlespeech_ctcdecoders.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/root/anaconda3/envs/asr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "infer_path.py", line 24, in <module>
    predictor = PPASRPredictor(configs=args.configs,
  File "/data/Speech/PPASR/ppasr/predict.py", line 73, in __init__
    self.__init_decoder()
  File "/data/Speech/PPASR/ppasr/predict.py", line 96, in __init_decoder
    from ppasr.decoders.beam_search_decoder import BeamSearchDecoder
  File "/data/Speech/PPASR/ppasr/decoders/beam_search_decoder.py", line 3, in <module>
    from ppasr.decoders.swig_wrapper import Scorer, CTCBeamSearchDecoder
  File "/data/Speech/PPASR/ppasr/decoders/swig_wrapper.py", line 1, in <module>
    import paddlespeech_ctcdecoders
  File "/root/anaconda3/envs/asr/lib/python3.8/site-packages/paddlespeech_ctcdecoders.py", line 17, in <module>
    _paddlespeech_ctcdecoders = swig_import_helper()
  File "/root/anaconda3/envs/asr/lib/python3.8/site-packages/paddlespeech_ctcdecoders.py", line 16, in swig_import_helper
    return importlib.import_module('_paddlespeech_ctcdecoders')
  File "/root/anaconda3/envs/asr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory

**Comment by yeyupiaoling** [comment]
@account15222 是importlib的错误，你卸载重装试一下
