### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by kkkkll2020** [yeyupiaoling/PPASR#26]
执行create_data.py报错：
Traceback (most recent call last):
  File "create_data.py", line 39, in <module>
    max_test_manifest=args.max_test_manifest)
  File "/usr/local/PPASR/ppasr/trainer.py", line 138, in create_data
    num_workers=self.num_workers)
  File "/usr/local/PPASR/ppasr/utils/utils.py", line 196, in compute_mean_std
    num_workers=num_workers)
  File "/usr/local/PPASR/ppasr/data_utils/normalizer.py", line 40, in __init__
    self._compute_mean_std(manifest_path, num_samples, num_workers)
  File "/usr/local/PPASR/ppasr/data_utils/normalizer.py", line 94, in _compute_mean_std
    for i in range(len(means)):

**Comment by yeyupiaoling** [comment]
是不是你的数据有问题？

**Comment by kkkkll2020** [comment]
在线下载数据太慢，就用迅雷下载完直接上传了

**Comment by yeyupiaoling** [comment]
按照文档指定压缩文件路径就行了

**Comment by kkkkll2020** [comment]
可以了
