### ISSUE TITLE
单机多卡训练失败怎么办？

### ISSUE THREAD

**Issue by fan-wc** [yeyupiaoling/PPASR#38]
```
(paddle_env) D:\python\PPASR__TEST\PPASR>python -m paddle.distributed.launch --gpus '0,1' train.py
-----------  Configuration Arguments -----------
backend: auto
elastic_server: None
force: False
gpus: '0,1'
heter_devices:
heter_worker_num: None
heter_workers:
host: None
http_port: None
ips: 127.0.0.1
job_id: None
log_dir: log
np: None
nproc_per_node: None
run_mode: None
scale: 0
server_num: None
servers:
training_script: train.py
training_script_args: []
worker_num: None
workers:
------------------------------------------------
WARNING 2022-02-16 18:25:24,619 launch.py:423] Not found distinct arguments and compiled with cuda or xpu. Default use collective mode
launch train in GPU mode!
INFO 2022-02-16 18:25:24,621 launch_utils.py:528] Local start 2 processes. First process distributed environment info (Only For Debug):
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:55021               |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                PADDLE_TRAINER_ENDPOINTS         127.0.0.1:55021,127.0.0.1:55022       |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                       '0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                      '0,1'                    |
    |                     FLAGS_selected_gpus                       '0                      |
    |             FLAGS_selected_accelerators                       '0                      |
    +=======================================================================================+

INFO 2022-02-16 18:25:24,621 launch_utils.py:532] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
子目录或文件 -p 已经存在。
处理: -p 时出错。
子目录或文件 log 已经存在。
处理: log 时出错。
子目录或文件 -p 已经存在。
处理: -p 时出错。
子目录或文件 log 已经存在。
处理: log 时出错。
launch proc_id:16392 idx:0
launch proc_id:18756 idx:1
Traceback (most recent call last):
  File "train.py", line 4, in <module>
    from ppasr.trainer import PPASRTrainer
  File "D:\python\PPASR__TEST\PPASR\ppasr\trainer.py", line 11, in <module>
    import paddle
  File "D:\python\anaconda3\envs\paddle_env\lib\site-packages\paddle\__init__.py", line 293, in <module>
    from .hapi import Model  # noqa: F401
  File "D:\python\anaconda3\envs\paddle_env\lib\site-packages\paddle\hapi\__init__.py", line 25, in <module>
    logger.setup_logger()
  File "D:\python\anaconda3\envs\paddle_env\lib\site-packages\paddle\hapi\logger.py", line 47, in setup_logger
    local_rank = ParallelEnv().local_rank
  File "D:\python\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\parallel.py", line 121, in __init__
    self._device_id = int(selected_gpus[0])
ValueError: invalid literal for int() with base 10: "'0"
INFO 2022-02-16 18:25:30,788 launch_utils.py:341] terminate all the procs
ERROR 2022-02-16 18:25:30,788 launch_utils.py:604] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.
INFO 2022-02-16 18:25:33,790 launch_utils.py:341] terminate all the procs
INFO 2022-02-16 18:25:33,790 launch.py:311] Local processes completed.
```

**Comment by yeyupiaoling** [comment]
你用Ubuntu测试吧，windows不确定是否这次多卡训练
