### ISSUE TITLE
如果想在预测结果的加上该预测的时间段 我该在哪里做一些改造

### ISSUE THREAD

**Issue by a00147600** [yeyupiaoling/PPASR#82]
这个问题可能有点过分 想请大佬指点一二。
得分: 82, 消耗时间：4275ms, 识别结果: 嗯哈您好您拨叫的用户暂时无人接听
我想知道对应的文字是录音的哪个时间段的。

**Comment by yeyupiaoling** [comment]
使用流式识别的方式可以计算得到。

**Comment by a00147600** [comment]
> 使用流式识别的方式可以计算得到。

谢谢 但我还有许多问题。。
快速部署的infer_path.py识别可以认为是流式识别么？
计算的具体位置在ppasr/predict.py文件么？

**Comment by yeyupiaoling** [comment]
类似这样，但是还不完善。并且只能用贪心解码策略，这个解码没有集束搜索解码准确率高

https://github.com/yeyupiaoling/PPASR/blob/5920316281e5ba194e2ceb822c49f5eb7d3af253/infer_path.py#L66-L87

**Comment by a00147600** [comment]
> 

非常奇怪 我试了下准确率的确不高 但是 #短语音识别 识别效果不错。切换到这个里面就差的好多。。。
分段结果：消耗时间：1111ms, 识别结果: , 得分: 0
分段结果：消耗时间：1033ms, 识别结果: , 得分: 0
分段结果：消耗时间：1014ms, 识别结果: 就帮, 得分: 28
分段结果：消耗时间：663ms, 识别结果: 就帮帮我把不还少常我我申, 得分: 34
整一句结果：消耗时间：4098ms, 识别结果: 就帮他不把不我少常我我是, 得分: 33
短语音：
得分: 82, 消耗时间：10280ms, 识别结果: 嗯哈您好您拨叫的用户暂时无人接听请您稍后再拨骚再次得一家喽有是哪的没了包莎那钱妹的您好您拨叫的用户暂时无人接听

**Comment by a00147600** [comment]
> 类似这样，但是还不完善。并且只能用贪心解码策略，这个解码没有集束搜索解码准确率高
> 
> https://github.com/yeyupiaoling/PPASR/blob/5920316281e5ba194e2ceb822c49f5eb7d3af253/infer_path.py#L66-L87

非常奇怪 我试了下准确率的确不高 但是 #短语音识别 识别效果不错。切换到这个里面就差的好多。。。
分段结果：消耗时间：1111ms, 识别结果: , 得分: 0
分段结果：消耗时间：1033ms, 识别结果: , 得分: 0
分段结果：消耗时间：1014ms, 识别结果: 就帮, 得分: 28
分段结果：消耗时间：663ms, 识别结果: 就帮帮我把不还少常我我申, 得分: 34
整一句结果：消耗时间：4098ms, 识别结果: 就帮他不把不我少常我我是, 得分: 33
短语音：
得分: 82, 消耗时间：10280ms, 识别结果: 嗯哈您好您拨叫的用户暂时无人接听请您稍后再拨骚再次得一家喽有是哪的没了包莎那钱妹的您好您拨叫的用户暂时无人接听

**Comment by yeyupiaoling** [comment]
这不应该啊，整一句结果和短语音的方式是一样的

**Comment by a00147600** [comment]
> 这不应该啊，整一句结果和短语音的方式是一样的
[tes1.zip](https://github.com/yeyupiaoling/PPASR/files/8946592/tes1.zip)
我的代码因为音频和源代码存在异常参数做了一点改动 。大佬可以看下这份音频的具体效果。
如果我按源代码去运行会有异常参数init_state_c_box=state_c 我把这个去掉了 
这个音频直接用real_time_predict_demo（）会报错:
Traceback (most recent call last):
  File "infer_path.py", line 99, in <module>
    real_time_predict_demo()
  File "infer_path.py", line 81, in real_time_predict_demo
    wf = wave.open(args.wav_path, 'rb')
  File "F:\Anaconda3\envs\ppasr\lib\wave.py", line 510, in open
    return Wave_read(f)
  File "F:\Anaconda3\envs\ppasr\lib\wave.py", line 164, in __init__
    self.initfp(f)
  File "F:\Anaconda3\envs\ppasr\lib\wave.py", line 144, in initfp
    self._read_fmt_chunk(chunk)
  File "F:\Anaconda3\envs\ppasr\lib\wave.py", line 269, in _read_fmt_chunk
    raise Error('unknown format: %r' % (wFormatTag,))
wave.Error: unknown format: 17
我用工具sox sox tes1.wav -b 16 -e signed-integer testes1.wav 转换了 开始正常运行 但结果出入很大

**Comment by a00147600** [comment]
> 这不应该啊，整一句结果和短语音的方式是一样的


我的代码因为音频和源代码存在异常参数做了一点改动 。大佬可以看下这份音频的具体效果。
如果我按源代码去运行会有异常参数init_state_c_box=state_c 我把这个去掉了
这个音频直接用real_time_predict_demo（）会报错:
Traceback (most recent call last):
File "infer_path.py", line 99, in
real_time_predict_demo()
File "infer_path.py", line 81, in real_time_predict_demo
wf = wave.open(args.wav_path, 'rb')
File "F:\Anaconda3\envs\ppasr\lib\wave.py", line 510, in open
return Wave_read(f)
File "F:\Anaconda3\envs\ppasr\lib\wave.py", line 164, in init
self.initfp(f)
File "F:\Anaconda3\envs\ppasr\lib\wave.py", line 144, in initfp
self._read_fmt_chunk(chunk)
File "F:\Anaconda3\envs\ppasr\lib\wave.py", line 269, in _read_fmt_chunk
raise Error('unknown format: %r' % (wFormatTag,))
wave.Error: unknown forma
[tes1.zip](https://github.com/yeyupiaoling/PPASR/files/8946609/tes1.zip)
t: 17
我用工具sox sox tes1.wav -b 16 -e signed-integer testes1.wav 转换了 开始正常运行 但结果出入很大

**Comment by yeyupiaoling** [comment]
init_state_c_box这个不能去掉。运行会有异常是因为前段时间代码和模型有更新，下载最新的代码和模型就没有问题。

**Comment by a00147600** [comment]
> init_state_c_box这个不能去掉。运行会有异常是因为前段时间代码和模型有更新，下载最新的代码和模型就没有问题。

我更新了代码 保留了旧的模型。
执行infer_path.py 会有这个问题
Traceback (most recent call last):
  File "infer_path.py", line 39, in <module>
    feature_method=args.feature_method)
  File "F:\PPASR-master\ppasr\predict.py", line 101, in __init__
    self.init_state_c_box_handle = self.predictor.get_input_handle('init_state_c_box')
RuntimeError: (PreconditionNotMet) The variable named init_state_c_box is not found in the scope of the executor.
  [Hint: scope->FindVar(name) should not be null.] (at ..\paddle\fluid\inference\api\analysis_predictor.cc:1210)

我已经更新了依赖文件
是旧的模型的问题吗？

**Comment by yeyupiaoling** [comment]
嗯，下载新的模型

**Comment by a00147600** [comment]
> 嗯，下载新的模型

因为我是自己训练的 我用python export_model.py --resume_model=models/deepspeech2/epoch_50/ 命令执行了我旧的训练好的预训练模型导出后可以预测了 但又回到了上面的问题。两次结果不一致。我跟源代码现在是一直的了。我的录音文件不同 因为实时预测上面的tes1.wav文件依然报错：
Traceback (most recent call last):
  File "infer_path.py", line 92, in <module>
    real_time_predict_demo()
  File "infer_path.py", line 74, in real_time_predict_demo
    wf = wave.open(args.wav_path, 'rb')
  File "F:\Anaconda3\envs\ppasr\lib\wave.py", line 510, in open
    return Wave_read(f)
  File "F:\Anaconda3\envs\ppasr\lib\wave.py", line 164, in __init__
    self.initfp(f)
  File "F:\Anaconda3\envs\ppasr\lib\wave.py", line 144, in initfp
    self._read_fmt_chunk(chunk)
  File "F:\Anaconda3\envs\ppasr\lib\wave.py", line 269, in _read_fmt_chunk
    raise Error('unknown format: %r' % (wFormatTag,))
wave.Error: unknown format: 17

**Comment by yeyupiaoling** [comment]
我查出你的问题了，是音频格式的问题。
音频格式应该要这样的：nchannels=1, sampwidth=2(PyAudio的是format=pyaudio.paInt16), framerate=16000
