### ISSUE TITLE
big模型有个报错

### ISSUE THREAD

**Issue by wangcc57** [yeyupiaoling/PPASR#93]
big模型使用工程里自带的wav没问题,换了个我自己的wav报错,是需要更新最新代码吗?

```
Traceback (most recent call last):
  File "infer_path.py", line 97, in <module>
    predict_audio()
  File "infer_path.py", line 61, in predict_audio
    score, text = predictor.predict(audio_path=args.wav_path, to_an=args.to_an)
  File "/data/PPASR/ppasr/predict.py", line 184, in predict
    self.predictor.run()
OSError: In user code:

    File "export_model.py", line 24, in <module>
      trainer.export(save_model_path=args.save_model, resume_model=args.resume_model)
    File "/data/PPASR/ppasr/trainer.py", line 533, in export
      paddle.jit.save(layer=model, path=infer_model_path, input_spec=input_spec)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 629, in wrapper
      func(layer, path, input_spec, **configs)
    File "/usr/local/python3/lib/python3.8/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 867, in save
      concrete_program = static_forward.concrete_program_specify_input_spec(
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 527, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 785, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "/usr/local/python3/lib/python3.8/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 733, in from_func_spec
      outputs = static_func(*inputs)
    File "/data/PPASR/ppasr/model_utils/utils.py", line 59, in forward
      logits, _, final_chunk_state_h_box, final_chunk_state_c_box = self.model(x, audio_len, init_state_h_box, init_state_c_box)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/data/PPASR/ppasr/model_utils/deepspeech2/model.py", line 53, in forward
      x, final_chunk_state_h_box, final_chunk_state_c_box = self.rnn(x, x_lens, init_state_h_box, init_state_c_box)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmp172gmmjh.py", line 60, in forward
      [x_lens, init_state_list, i, x] = paddle.jit.dy2static.convert_while_loop(
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 45, in convert_while_loop
      loop_vars = _run_py_while(cond, body, loop_vars)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 59, in _run_py_while
      loop_vars = body(*loop_vars)
    File "/data/PPASR/ppasr/model_utils/deepspeech2/rnn.py", line 65, in forward
      x, final_state = self.rnn[i](x, x_lens, init_state_list[i])
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/data/PPASR/ppasr/model_utils/deepspeech2/rnn.py", line 21, in forward
      x, final_state = self.rnn(x, init_state, x_lens)  # [B, T, D]
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/nn/layer/rnn.py", line 1077, in forward
      return self._cudnn_impl(inputs, initial_states, sequence_length)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/nn/layer/rnn.py", line 1051, in _cudnn_impl
      self._helper.append_op(
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/layer_object_helper.py", line 48, in append_op
      return self.main_program.current_block().append_op(
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3615, in append_op
      op = Operator(
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2635, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUDNN error(3), CUDNN_STATUS_BAD_PARAM. 
      [Hint: 'CUDNN_STATUS_BAD_PARAM'.  An incorrect value or parameter was passed to the function. To correct, ensure that all the parameters being passed have valid values.  ] (at /paddle/paddle/fluid/pla
tform/device/gpu/cuda/cudnn_helper.h:287)
      [operator < rnn > error]
```

**Comment by yeyupiaoling** [comment]
是不是音频太长了，太长就用长语音识别。
太短也会报这个错误。

**Comment by yeyupiaoling** [comment]
test_long.wav这个你用短语音识别也正常吗？不应该的。太长直接输入肯定会显存不足的

**Comment by wangcc57** [comment]
正常的,P40直接跑test_long.wav不报错

**Comment by yeyupiaoling** [comment]
你换成长语音识别怎么样？

**Comment by wangcc57** [comment]
长语音可以,这就不科学了,难道我的wav有毒吗 :(

**Comment by yeyupiaoling** [comment]
不可能吧，我还是觉得是因为音频太长的。因为输入太长也是类似的错误。

**Comment by wangcc57** [comment]
不过问题不大,反正也是要截成单句处理的,Wenet数据集你训练过吗?需要什么样的资源要多久?

我测试了下Wenet数据集训练,发现第一个epoch的loss一直在涨,是哪里姿势不对吗?

**Comment by yeyupiaoling** [comment]
没训练过，第一个epoch训练时，数据集是从短到长排序的，所以这种情况是正常的。

**Comment by wangcc57** [comment]
我还发现双卡比单卡还慢,有的时候还会卡住.

**Comment by yeyupiaoling** [comment]
不应该，你看剩余时间的吗？你看哪个日志？

**Comment by yeyupiaoling** [comment]
多卡的日志是再log目录下的，对应每个卡的日志。

**Comment by yeyupiaoling** [comment]
你看看是不是正常训练。

**Comment by yeyupiaoling** [comment]
这么奇怪？你的两个卡一样的吗？

**Comment by yeyupiaoling** [comment]
是不是数据预处理跟不上？

**Comment by wangcc57** [comment]
必须一样的,专门插了2个一样的卡
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.73.08    Driver Version: 510.73.08    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P40           Off  | 00000000:04:00.0 Off |                  Off |
| N/A   43C    P0    51W / 250W |      0MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P40           Off  | 00000000:83:00.0 Off |                  Off |
| N/A   41C    P0    50W / 250W |      0MiB / 24576MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by yeyupiaoling** [comment]
2张卡都是100%吗？

**Comment by yeyupiaoling** [comment]
你分别用单卡测试2卡试试？你的卡1没有日志输出，有可能是它导致整体变慢的。

**Comment by wangcc57** [comment]
我试试

**Comment by wangcc57** [comment]
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.73.08    Driver Version: 510.73.08    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P40           Off  | 00000000:04:00.0 Off |                  Off |
| N/A   39C    P0    50W / 250W |      0MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P40           Off  | 00000000:83:00.0 Off |                  Off |
| N/A   53C    P0   200W / 250W |   4601MiB / 24576MiB |     95%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    1   N/A  N/A     12426      C   python3                          4599MiB |
+-----------------------------------------------------------------------------+

[2022-07-15 10:44:59.195437] 训练数据：14660592
[2022-07-15 10:45:04.379965] Train epoch: [1/65], batch: [0/458143], loss: 88.21230, learning rate: 0.00005000, eta: 1786 days, 13:44:50
[2022-07-15 10:45:17.785773] Train epoch: [1/65], batch: [100/458143], loss: 15.96248, learning rate: 0.00005000, eta: 46 days, 3:21:53
[2022-07-15 10:45:30.826052] Train epoch: [1/65], batch: [200/458143], loss: 13.98875, learning rate: 0.00005000, eta: 44 days, 20:11:12
[2022-07-15 10:45:43.916232] Train epoch: [1/65], batch: [300/458143], loss: 18.24256, learning rate: 0.00005000, eta: 45 days, 0:27:07
[2022-07-15 10:45:57.125810] Train epoch: [1/65], batch: [400/458143], loss: 17.17925, learning rate: 0.00005000, eta: 45 days, 10:49:58
[2022-07-15 10:46:10.207853] Train epoch: [1/65], batch: [500/458143], loss: 12.79642, learning rate: 0.00005000, eta: 45 days, 0:00:46




+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.73.08    Driver Version: 510.73.08    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P40           Off  | 00000000:04:00.0 Off |                  Off |
| N/A   51C    P0   154W / 250W |   4601MiB / 24576MiB |     97%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P40           Off  | 00000000:83:00.0 Off |                  Off |
| N/A   47C    P0    51W / 250W |      0MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     12622      C   python3                          4599MiB |
+-----------------------------------------------------------------------------+

[2022-07-15 10:48:46.283469] 训练数据：14660592
[2022-07-15 10:48:52.645588] Train epoch: [1/65], batch: [0/458143], loss: 87.22278, learning rate: 0.00005000, eta: 2192 days, 3:52:18
[2022-07-15 10:49:05.040063] Train epoch: [1/65], batch: [100/458143], loss: 15.78344, learning rate: 0.00005000, eta: 42 days, 15:40:24
[2022-07-15 10:49:17.719734] Train epoch: [1/65], batch: [200/458143], loss: 14.05792, learning rate: 0.00005000, eta: 43 days, 15:09:58
[2022-07-15 10:49:30.346088] Train epoch: [1/65], batch: [300/458143], loss: 18.16205, learning rate: 0.00005000, eta: 43 days, 10:08:28

**Comment by wangcc57** [comment]
分开单独跑都正常,多卡一起跑就慢还卡住

**Comment by yeyupiaoling** [comment]
这么神奇？我使用一般会快一半的时间。你试试设置读取数据线程16试试看、你CPU应该不少于16核吧？
https://github.com/yeyupiaoling/PPASR/blob/e4ed0f821cfdaaf55741650b4db601cce53378c0/train.py#L10

**Comment by wangcc57** [comment]
这个我已经改成32了,CPU是32核的

**Comment by yeyupiaoling** [comment]
你其他的并行任务正常吗？你的nccl版本是多少？

**Comment by wangcc57** [comment]
nccl-local-repo-rhel7-2.12.12-cuda11.7-1.0-1.x86_64
我在怀疑cuda的版本问题,GPU显示是11.6的但是装了11.7的也能用,我换成11.6试试

**Comment by yeyupiaoling** [comment]
好

**Comment by wangcc57** [comment]
还是一样的,GPU跑满,但是很慢

**Comment by yeyupiaoling** [comment]
这也太奇怪了。你直接用deepspeech试试看。

**Comment by yeyupiaoling** [comment]
你在其他的多卡任务中，有没有正常？

**Comment by wangcc57** [comment]
服务器周末维护了,还没测试.
