### ISSUE TITLE
create_data.py报错ValueError: negative dimensions are not allowed

### ISSUE THREAD

**Issue by a00147600** [yeyupiaoling/PPASR#98]
非常奇怪。我之前遇到过这个问题。但是此时我的训练集变小了依然会报错。不是非常能理解。
```
------------------------------------------------
开始生成数据列表...
100%|█████████████████████████████████████████████████████████████████████████| 165880/165880 [26:41<00:00, 103.60it/s]
完成生成数据列表，数据集总长度为161.37小时！
======================================================================
开始生成噪声数据列表...
噪声音频文件为空，已跳过！
======================================================================
开始生成数据字典...
100%|███████████████████████████████████████████████████████████████████████| 165548/165548 [00:03<00:00, 47778.39it/s]
100%|█████████████████████████████████████████████████████████████████████████████| 332/332 [00:00<00:00, 47563.24it/s]
数据字典生成完成！
======================================================================
开始抽取10000条数据计算均值和标准值...
F:\Anaconda3\envs\ppasr\lib\site-packages\paddle\fluid\reader.py:481: UserWarning: DataLoader with multi-process mode is not supported on MacOs and Windows currently. Please use signle-process mode with num_workers = 0 instead
  "DataLoader with multi-process mode is not supported on MacOs and Windows currently." \
  0%|▎                                                                               | 1/313 [00:14<1:17:55, 14.99s/it]W0801 15:40:32.614073 180432 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.6, Runtime API Version: 10.2
W0801 15:40:32.798592 180432 gpu_context.cc:306] device: 0, cuDNN Version: 7.6.
  2%|█▊                                                                                | 7/313 [00:20<09:12,  1.80s/it]F:\Anaconda3\envs\ppasr\lib\site-packages\numpy\core\fromnumeric.py:3441: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
F:\Anaconda3\envs\ppasr\lib\site-packages\numpy\core\_methods.py:189: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)
Exception in thread Thread-4:
Traceback (most recent call last):
  File "F:\Anaconda3\envs\ppasr\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "F:\Anaconda3\envs\ppasr\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "F:\Anaconda3\envs\ppasr\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 216, in _thread_loop
    self._thread_done_event)
  File "F:\Anaconda3\envs\ppasr\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 121, in fetch
    data.append(self.dataset[idx])
  File "F:\PPASR-master\ppasr\data_utils\normalizer.py", line 114, in __getitem__
    feature = self.audio_featurizer.featurize(audio)
  File "F:\PPASR-master\ppasr\data_utils\featurizer\audio_featurizer.py", line 71, in featurize
    stride_ms=self._stride_ms, window_ms=self._window_ms)
  File "F:\PPASR-master\ppasr\data_utils\featurizer\audio_featurizer.py", line 92, in _compute_linear
    windows = np.lib.stride_tricks.as_strided(samples, shape=nshape, strides=nstrides)
  File "F:\Anaconda3\envs\ppasr\lib\site-packages\numpy\lib\stride_tricks.py", line 104, in as_strided
    array = np.asarray(DummyArray(interface, base=x))
ValueError: negative dimensions are not allowed
```

**Comment by yeyupiaoling** [comment]
是不是你的音频有很短的，你看下dataset下的manifest.train，看看最短的音频是多少？

**Comment by a00147600** [comment]
> 是不是你的音频有很短的，你看下dataset下的manifest.train，看看最短的音频是多少？

大佬指的是duration这个的值吗 我执行create时以往的没有删除 存在0.00的 我想知道多少duration低的需要删除

**Comment by yeyupiaoling** [comment]
这里给个最小0.5吧，后面我会修复
https://github.com/yeyupiaoling/PPASR/blob/62ed3fc7af2e4a8fc264fac74c312c01fc4a3bf7/ppasr/data_utils/utils.py#L8

**Comment by a00147600** [comment]
> 这里给个最小0.5吧，后面我会修复
> 
> https://github.com/yeyupiaoling/PPASR/blob/62ed3fc7af2e4a8fc264fac74c312c01fc4a3bf7/ppasr/data_utils/utils.py#L8

谢谢 这个问题解决了
